description: 手眼标定预设位置配置
notes: 关节角度单位为度制，范围建议在±120度内
pose_count: 26
poses:
- joint_angles:
  - -0.0
  - -30.0
  - 30.0
  - 0.0
  - 30.0
  - 0.0
  name: pose_1
- joint_angles:
  - -5.1
  - -29.6
  - 29.9
  - 27.1
  - 33.2
  - -20.8
  name: pose_2
- joint_angles:
  - -5.2
  - -26.1
  - 24.6
  - 19.4
  - 49.2
  - -14.5
  name: pose_3
- joint_angles:
  - -4.8
  - -21.8
  - 19.3
  - 14.9
  - 64.7
  - -16.5
  name: pose_4
- joint_angles:
  - 3.8
  - -22.5
  - 20.0
  - -12.2
  - 62.2
  - 8.4
  name: pose_5
- joint_angles:
  - 4.0
  - -25.4
  - 23.4
  - -14.2
  - 51.7
  - 39.7
  name: pose_6
- joint_angles:
  - 1.6
  - -26.3
  - 24.4
  - -5.9
  - 47.8
  - 27.7
  name: pose_7
- joint_angles:
  - 13.1
  - -27.8
  - 27.1
  - -15.3
  - 37.7
  - 21.9
  name: pose_8
- joint_angles:
  - 11.0
  - -29.1
  - 29.1
  - -6.7
  - 30.3
  - 13.9
  name: pose_9
- joint_angles:
  - 7.4
  - -23.9
  - 21.6
  - 8.2
  - 53.9
  - -13.0
  name: pose_10
- joint_angles:
  - 8.2
  - -22.0
  - 19.2
  - 5.0
  - 61.1
  - 4.4
  name: pose_11
- joint_angles:
  - 15.7
  - -22.3
  - 20.1
  - -19.4
  - 60.7
  - 42.2
  name: pose_12
- joint_angles:
  - 15.5
  - -27.3
  - 26.9
  - -25.7
  - 40.5
  - 6.2
  name: pose_13
- joint_angles:
  - -13.9
  - -26.6
  - 25.8
  - 19.8
  - 39.2
  - -27.1
  name: pose_14
- joint_angles:
  - -19.6
  - -25.8
  - 26.6
  - 44.7
  - 45.0
  - -38.9
  name: pose_15
- joint_angles:
  - -20.4
  - -21.3
  - 20.6
  - 37.4
  - 62.6
  - -48.7
  name: pose_16
- joint_angles:
  - -17.7
  - -18.1
  - 15.9
  - 25.2
  - 72.5
  - -31.2
  name: pose_17
- joint_angles:
  - -10.2
  - -20.5
  - 17.4
  - 2.0
  - 63.2
  - -10.5
  name: pose_18
- joint_angles:
  - -8.8
  - -23.0
  - 20.4
  - -2.8
  - 54.2
  - 18.6
  name: pose_19
- joint_angles:
  - -12.2
  - -27.7
  - 27.5
  - 13.9
  - 32.9
  - -12.3
  name: pose_20
- joint_angles:
  - 2.7
  - -25.0
  - 2.2
  - -5.7
  - 59.7
  - 5.7
  name: pose_21
- joint_angles:
  - -4.8
  - -26.0
  - 4.0
  - 17.3
  - 56.4
  - 4.0
  name: pose_22
- joint_angles:
  - -4.2
  - -15.4
  - -9.7
  - 12.6
  - 93.6
  - -14.3
  name: pose_23
- joint_angles:
  - 7.2
  - -16.3
  - -8.4
  - -16.7
  - 90.8
  - 5.5
  name: pose_24
- joint_angles:
  - 3.3
  - -21.2
  - -3.0
  - -6.6
  - 74.0
  - 30.2
  name: pose_25
- joint_angles:
  - 8.3
  - -23.7
  - 1.0
  - -21.5
  - 65.6
  - 22.8
  name: pose_26
